# Makefile for Lab03-Blinky, ELEC424 Fall 2014
# Authors: Jie Liao, Abeer Javed, Steven Arroyo. Rice University 
# Derived from the crazyflie-firmware Makefile

# Filename defination
FILENAME = $(notdir $(CURDIR))

# Path Definitions
PRO_ROOT = .
STM_ROOT = STM32F10x_StdPeriph_Lib_V3.5.0
STM_LIB =  $(STM_ROOT)/Libraries
STARTUP_PATH = $(STM_LIB)/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/TrueSTUDIO

# Compiler 
CC = arm-none-eabi-gcc

# Particular processor
PROCESSOR = -mcpu=cortex-m3 -mthumb

# Directories of used header files
INCLUDE = ??

# STM chip specific flags
STFLAGS = -DSTM32F10X_MD -include $(PRO_ROOT)/stm32f10x_conf.h

# Define the compiler flags
CFLAGS = -O0 -g3 $(PROCESSOR) $(INCLUDE) $(STFLAGS) -Wl,--gc-sections -T $(PRO_ROOT)/stm32_flash.ld

# Build all relevant files and create .elf
all:
	@$(CC) $(CFLAGS) $(STARTUP_PATH)/startup_stm32f10x_md.s ??

# Program .elf into Crazyflie flash memory via the busblaster
flash:
	@openocd $(OCDFLAG) -c "flash write_image erase $(FILENAME).elf" -c "verify_image $(FILENAME).elf" -c "reset run" -c shutdown

# Runs OpenOCD, opens GDB terminal, and establishes connection with Crazyflie
debug:
	@openocd $(OCDFLAG) &
	@arm-none-eabi-gdb $(FILENAME).elf --eval-command="target remote:3333"
	@ps axf | grep openocd |grep -v grep | awk '{print "kill -9" $$1}' | sh

# Remove all files generated by target 'all'
clean:
	??
